  frontend:
    container_name: exam-ui
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ew-net
    env_file:
      - ./frontend/.env
