services:
  exam-whisperer:
    container_name: exam-whisperer
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SERVER_PORT: 8000
    volumes:
      - ./:/app
      - /mnt/extra/uv-cache:/root/.cache/uv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whisper-api.rule=Host(`whisper.alokranjan.me`)"
      - "traefik.http.routers.whisper-api.entrypoints=websecure"
      - "traefik.http.routers.whisper-api.tls=true"
      - "traefik.http.routers.whisper-api.service=exam-whisperer"
      - "traefik.http.services.exam-whisperer.loadbalancer.server.port=8000"
    networks:
      - web
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: ew-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web

networks:
  web:
    external: true

volumes:
  pgdata:
